name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/gh-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install packages from frontend/package.json
      - name: Install deps
        working-directory: frontend
        run: npm ci

      # Build the Vite app (outputs to frontend/dist)
      - name: Build
        working-directory: frontend
        env:
          # If you committed frontend/.env.production you can remove this line.
          REACT_APP_API_BASE_URL: https://moneymate-1-30px.onrender.com
        run: npm run build

      # Enable Pages for this repo automatically
      - name: Setup Pages (auto-enable)
        uses: actions/configure-pages@v5
        with:
          enablement: true

      # Upload the built site (Vite builds to 'dist')
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
