name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '!**.md'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          # Make sure .env.production is committed in frontend/ with your Render URL
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL || '' }}
        run: npm run build

      # Publish the compiled app in frontend/build to the gh-pages branch
      - name: Deploy to gh-pages
        run: npx gh-pages -d build -u "github-actions-bot <actions@github.com>"
